CHILD_ADDITION_SUCCEEDED = 'CHILD_ADDITION_SUCCEEDED'
CHILD_ADDITION_FAILED = 'CHILD_ADDITION_FAILED'

SPOUSE_ADDITION_SUCCEEDED = 'SPOUSE_ADDITION_SUCCEEDED'
SPOUSE_ADDITION_FAILED = 'SPOUSE_ADDITION_FAILED'

PERSON_NOT_FOUND = 'PERSON_NOT_FOUND'
NONE = 'NONE'
